name: weather
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  floor: ^1.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  http: ^1.1.0
  rxdart: ^0.27.7
  skeletonizer: ^0.8.0
  sqflite: ^2.3.0

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  floor_generator: ^1.4.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
